### ISSUE TITLE
fix: destructuring fields from formState not reactive

### ISSUE THREAD

**Issue by kylegl** [vue-hooks-form/vue-hooks-form#20]
I was testing the form with the zod resolver. When destructuring formState properties isDirty, isValid, dirtyFields. Their value is not reactive. However, destructuring errors from formState is reactive. 

Does not work:

`const { formState: { isDirty, dirtyFields, isValid} = useForm(...)}`

works:

```
const { formState } = useForm(...)

formState.isValid (reactive)
```

Need to play with this a bit more. Here is a minimal reproduction.

[codesandbox](https://codesandbox.io/p/github/kylegl/vue-hooks-form/fix/form-state-reactivity?file=%2FREADME.md&layout=%257B%2522activeFilepath%2522%253A%2522%252Fplayground%252Fsrc%252FApp.vue%2522%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522fullScreenDevtools%2522%253Afalse%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522vertical%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522DEVTOOLS_PANELS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clgwu746m00mn356lvygupgue%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clgwu746m00mn356lvygupgue%2522%253A%257B%2522id%2522%253A%2522clgwu746m00mn356lvygupgue%2522%252C%2522activeTabId%2522%253A%2522clgwu874a00qc356l12y7jjwl%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clgwu746m00mm356lduiunewb%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clgwu76do0043g2fwf9llc4j3%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clgwu874a00qc356l12y7jjwl%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%257D%252C%2522showSidebar%2522%253Atrue%252C%2522showDevtools%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%252C%2522editorPanelSize%2522%253A38.57350800582242%252C%2522devtoolsPanelSize%2522%253A44.09752547307133%257Dl)

**Comment by elonehoo** [comment]
aha! let's think about what to do
