### ISSUE TITLE
updating default values?

### ISSUE THREAD

**Issue by kylegl** [vue-hooks-form/vue-hooks-form#44]
Hello Elone,

I have a situation where I am submitting the form and then want to continue using it with the submitted values set as the new default values. I need a way to update the defaults. Is that possible currently?

flow:
default values -> useForm -> change form values -> submit -> on success updated values are set as defaults

**Comment by elonehoo** [comment]
Let me try. I haven't had a need for this.

**Comment by kylegl** [comment]
i found a way to kinda hack it. 
```
watch(() => formState.isSubmitted, () => {
  const newValues = getValues()

  Object.entries(newValues) .forEach(([key ,value]) => { 
		// updates default values
		formState.defaultValues[key] = value

		// triggers the dirty state to reset 
		setValue(key, value)
	} 
})
```

**Comment by elonehoo** [comment]
It looks like we can write the default values in here
<img width="1710" alt="image" src="https://github.com/vue-hooks-form/vue-hooks-form/assets/43719490/4f116c61-f63f-4eb6-bda6-4a36ee5818f9">

**Comment by elonehoo** [comment]
I don't know if that satisfies you.
https://github.com/vue-hooks-form/vue-hooks-form/assets/43719490/f0595c22-ac45-4ebd-b179-fccd25388abc

**Comment by kylegl** [comment]
Cool I'll check it out!
