### ISSUE TITLE
Release workflow

### ISSUE THREAD

**Issue by kylegl** [vue-hooks-form/vue-hooks-form#54]
Thanks for the assist on that pr!

Whats your release process?

**Comment by elonehoo** [comment]
Let's try running `pnpm run release`.

**Comment by kylegl** [comment]
ok on main branch?

**Comment by elonehoo** [comment]
No problem. Be bold.

**Comment by kylegl** [comment]
Well that was easy. How you do that??

**Comment by elonehoo** [comment]
This is all thanks to the powerful output of [antfu](https://github.com/antfu).

- [bumpp](https://github.com/antfu/bumpp)
- [changelogithub](https://github.com/antfu/changelogithub)
- [release ci](https://github.com/antfu/changelogithub/blob/main/.github/workflows/release.yml)

**Comment by kylegl** [comment]
Im literally watching the nuxt stream he recently uploaded on youtube haha. Dudes my idol

**Comment by elonehoo** [comment]
Yes, he will be the idol of all Vue'er , he has the ability to create in ways that I can't even imagine.

**Comment by elonehoo** [comment]
aha?

**Comment by kylegl** [comment]
yeah definitely needed to build first. whoops

**Comment by kylegl** [comment]
all good now 💪

**Comment by elonehoo** [comment]
so cool
